#!/usr/bin/env python3
# -*- coding: utf-8; -*-

import sys
import os

import requests
import subprocess

def get_pr(token, branch):
    p = subprocess.Popen("git rev-parse --show-toplevel", stdout=subprocess.PIPE, shell=True)
    (output, err) = p.communicate()
    p_status = p.wait()
    repo = os.path.basename(output.decode()).strip()

    url = f'https://api.github.com/repos/CGHoussem/{repo}/pulls'
    headers = {
            'Accept': 'application/vnd.github+json',
            'Authorization': f'Bearer {token}',
            'X-GitHub-Api-Version': '2022-11-28'
    }
    params = {
            'head': f'CGHoussem:{branch}',
    }
    response = requests.get(url, params=params, headers=headers)

    if not response.ok:
        print(f'Unable to get pull requests ({response.status_code}): {response.reason}', file=sys.stderr)
        exit(1)
    jsonObj = response.json()

    if len(jsonObj) <= 0:
        return None

    return jsonObj[0]


def main(action, origin, branch):
    # Get GITHUB service token
    token = os.getenv('GITHUB_TOKEN')
    if token is None or len(token) == 0:
        print('Unable to get github token from environment variables', file=sys.stderr)
        exit(1)

    pr = get_pr(token, branch)

    if pr is None:
        print('You need to publish first (in order to create the PR)')
        exit(1)
    
    if pr['mergeable'] == 'null':
        print('A mergeability checking job is in progress..\n\
            Wait fot the job to complete and resubmit the request!')
        exit(1)
    elif pr['mergeable'] == 'false':
        print('Unable to merge PR due to failed checks.')
        exit(1)

if __name__ == '__main__':
    action = sys.argv[0].split('-')[-1]
    main(action, sys.argv[2], sys.argv[3])
