#!/usr/bin/env python3
# -*- coding: utf-8; -*-

import sys
import os
import re

import requests
import subprocess


def get_github_owner_from_git():
    # Get the remote URL of the Git repository
    try:
        remote_url_bytes = subprocess.check_output(['git', 'config', '--get', 'remote.origin.url'])
        remote_url = remote_url_bytes.decode().strip()
    except subprocess.CalledProcessError:
        print("Failed to retrieve Git remote URL.")
        return None

    # Regular expression patterns for matching GitHub repository URLs
    ssh_pattern = r'^git@github\.com:([^/]+)/.*$'
    https_pattern = r'^https://github\.com/([^/]+)/.*$'

    # Check if the remote URL matches GitHub repository URL patterns
    if re.match(ssh_pattern, remote_url):
        owner_name = re.match(ssh_pattern, remote_url).group(1)
    elif re.match(https_pattern, remote_url):
        owner_name = re.match(https_pattern, remote_url).group(1)
    else:
        print("Remote URL is not a GitHub repository.")
        return None

    return owner_name


def get_projet_prs(token, branch):
    p = subprocess.Popen("git rev-parse --show-toplevel", stdout=subprocess.PIPE, shell=True)
    (output, _) = p.communicate()
    _ = p.wait()
    repo = os.path.basename(output.decode()).strip()
    owner = get_github_owner_from_git()

    url = f'https://api.github.com/repos/{owner}/{repo}/pulls'
    headers = {
            'Accept': 'application/vnd.github+json',
            'Authorization': f'Bearer {token}',
            'X-GitHub-Api-Version': '2022-11-28'
    }
    params = {
            'head': f'{owner}:{branch}',
    }
    response = requests.get(url, params=params, headers=headers)

    if not response.ok:
        print(f'Unable to get pull requests ({response.status_code}): {response.reason}', file=sys.stderr)
        exit(1)
    jsonObj = response.json()

    if len(jsonObj) <= 0:
        return None

    return jsonObj

def get_pr(token, branch):
    prs = get_projet_prs(token, branch)
    if prs is None:
        return None
    pr_number = prs[0]['number']
    
    p = subprocess.Popen("git rev-parse --show-toplevel", stdout=subprocess.PIPE, shell=True)
    (output, _) = p.communicate()
    _ = p.wait()
    repo = os.path.basename(output.decode()).strip()
    owner = get_github_owner_from_git()

    url = f'https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}'
    headers = {
            'Accept': 'application/vnd.github+json',
            'Authorization': f'Bearer {token}',
            'X-GitHub-Api-Version': '2022-11-28'
    }
    params = {
            'head': f'{owner}:{branch}',
    }
    response = requests.get(url, params=params, headers=headers)

    if not response.ok:
        print(f'Unable to get the pull request #{pr_number} ({response.status_code}): {response.reason}', file=sys.stderr)
        exit(1)
    jsonObj = response.json()

    return jsonObj

def msg_merge_pr(token, branch, pr_number):
    p = subprocess.Popen("git rev-parse --show-toplevel", stdout=subprocess.PIPE, shell=True)
    (output, _) = p.communicate()
    _ = p.wait()
    repo = os.path.basename(output.decode()).strip()
    owner = get_github_owner_from_git()

    url = f'https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}'
    headers = {
        'Accept': 'application/vnd.github+json',
        'Authorization': f'Bearer {token}',
        'X-GitHub-Api-Version': '2022-11-28'
    }
    data = {
        'body': 'This PR has been merged via a git flow finish',
    }
    response = requests.patch(url, headers=headers, json=data)

    if not response.ok:
        print(f'Unable to patch the pull request ({response.status_code}): {response.reason}', file=sys.stderr)
        exit(1)

def main(action, origin, branch):
    # Get the owner of the project
    owner = get_github_owner_from_git()
    if owner is None:
        print('Unable to get the owner of the git project', file=sys.stderr)
        exit(1)
        
    # Get GITHUB service token
    token = os.getenv(f'GITHUB_{owner.upper()}_TOKEN')
    if token is None or len(token) == 0:
        print('Unable to get github token from environment variables', file=sys.stderr)
        exit(1)

    pr = get_pr(token, branch)

    if pr is None:
        print('You need to publish first (in order to create the PR)')
        exit(1)
    if pr['mergeable'] == 'null':
        print('A mergeability checking job is in progress..\n\
            Wait fot the job to complete and resubmit the request!')
        exit(1)
    elif pr['mergeable'] == 'false':
        print('Unable to merge PR due to failed checks.')
        exit(1)

    # update body of PR
    msg_merge_pr(token, branch, pr['number'])


if __name__ == '__main__':
    action = sys.argv[0].split('-')[-1]
    main(action, sys.argv[2], sys.argv[3])
