#!/usr/bin/env python3
# -*- coding: utf-8; -*-

import sys
import os

import requests
import subprocess

def get_pr(token, branch):
    p = subprocess.Popen("git rev-parse --show-toplevel", stdout=subprocess.PIPE, shell=True)
    (output, err) = p.communicate()
    p_status = p.wait()
    repo = os.path.basename(output.decode()).strip()

    url = f'https://api.github.com/repos/CGHoussem/{repo}/pulls'
    headers = {
            'Accept': 'application/vnd.github+json',
            'Authorization': f'Bearer {token}',
            'X-GitHub-Api-Version': '2022-11-28'
    }
    params = {
            'head': f'CGHoussem:{branch}',
    }
    response = requests.get(url, params=params, headers=headers)

    if not response.ok:
        print(f'Unable to get pull requests ({response.status_code}): {response.reason}', file=sys.stderr)
        exit(1)
    jsonObj = response.json()

    if len(jsonObj) <= 0:
        return None, None

    return jsonObj[0]['number'], jsonObj[0]['html_url']

def create_pr(token, branch):
    p = subprocess.Popen("git rev-parse --show-toplevel", stdout=subprocess.PIPE, shell=True)
    (output, err) = p.communicate()
    p_status = p.wait()
    repo = os.path.basename(output.decode()).strip()
    base = 'develop'
    if 'hotfix/' in branch or 'release/' in branch:
        base = 'master'

    url = f'https://api.github.com/repos/CGHoussem/{repo}/pulls'
    headers = {
        'Accept': 'application/vnd.github+json',
        'Authorization': f'Bearer {token}',
        'X-GitHub-Api-Version': '2022-11-28'
    }
    data = {
        'title': f'Merge {branch} to {base}',
        'head': f'CGHoussem:{branch}',
        'base': f'{base}',
    }
    response = requests.post(url, headers=headers, json=data)
    if not response.ok:
        print(f'Unable to get create a pull request ({response.status_code}): {response.reason}', file=sys.stderr)
        exit(1)

    try:
        pr_number = response.json()['number']
        pr_url = response.json()['html_url']
    except KeyError as err:
        print(f'Error getting id from response: {response.json()}', file=sys.stderr)
        exit(1)

    return pr_number, pr_url

def merge_pr(token, branch, pr_number):
    p = subprocess.Popen("git rev-parse --show-toplevel", stdout=subprocess.PIPE, shell=True)
    (output, err) = p.communicate()
    p_status = p.wait()
    repo = os.path.basename(output.decode()).strip()
    base = 'develop'
    if 'hotfix/' in branch or 'release/' in branch:
        base = 'master'

    url = f'https://api.github.com/repos/CGHoussem/{repo}/pulls/{pr_number}/merge'
    headers = {
        'Accept': 'application/vnd.github+json',
        'Authorization': f'Bearer {token}',
        'X-GitHub-Api-Version': '2022-11-28'
    }
    data = {
        'merge_method': 'squash',
    }
    response = requests.put(url, headers=headers, json=data)

    if not response.ok:
        print(f'Unable to merge the pull request ({response.status_code}): {response.reason}', file=sys.stderr)
        exit(1)

    return response.json()['message']

def msg_merge_pr(token, branch, pr_number):
    p = subprocess.Popen("git rev-parse --show-toplevel", stdout=subprocess.PIPE, shell=True)
    (output, err) = p.communicate()
    p_status = p.wait()
    repo = os.path.basename(output.decode()).strip()
    base = 'develop'
    if 'hotfix/' in branch or 'release/' in branch:
        base = 'master'

    url = f'https://api.github.com/repos/CGHoussem/{repo}/pulls/{pr_number}/merge'
    headers = {
        'Accept': 'application/vnd.github+json',
        'Authorization': f'Bearer {token}',
        'X-GitHub-Api-Version': '2022-11-28'
    }
    data = {
        'body': 'This PR has been merged via a git flow finish',
    }
    response = requests.patch(url, headers=headers, json=data)

    if not response.ok:
        print(f'Unable to patch the pull request ({response.status_code}): {response.reason}', file=sys.stderr)
        exit(1)

    return response.json()['message']

def git_reset_hard():
    subprocess.run(['git', 'reset', '--hard', 'HEAD~1'])

def git_fetch_pull():
    subprocess.run(['git', 'fetch'])
    subprocess.run(['git', 'pull'])

def git_delete_branch(branch):
    subprocess.run(['git', 'branch', 'delete', '-D', branch])

def git_push_tags():
    subprocess.run(['git', 'push', '--tags'])


def main(action, origin, branch):
    # Get GITHUB service token
    token = os.getenv('GITHUB_TOKEN')
    if token is None or len(token) == 0:
        print('Unable to get github token from environment variables', file=sys.stderr)
        exit(1)

    pr_number, pr_url = get_pr(token, branch)
    if action == 'publish':
        if pr_number is None:
            cr_pr = False
            while True:
                response = input("Would you like to create a PR (Y/n)? ").strip().lower()
                if response == 'y' or response == '':
                    cr_pr = True
                    break
                elif response == 'n':
                    break
                else:
                    print("Invalid input. Please try again.")
            if cr_pr:
                print('Creating a pull request..')
                pr_number, pr_url = create_pr(token, branch)
                print(f'Created a pull request ({pr_number}): {pr_url}')
        else:
            print(f'Updating pull request: {pr_url}')
    elif action == 'finish':
        if pr_number is None:
            print('You need to publish first (in order to create the PR)')
            exit(1)
        mr_msg = msg_merge_pr(token, branch, pr_number)
        print(mr_msg)

        git_reset_hard()
        git_fetch_pull()
        git_push_tags()

if __name__ == '__main__':
    action = sys.argv[0].split('-')[-1]
    main(action, sys.argv[2], sys.argv[3])
